{% set name = "skscope" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/skscope-{{ version }}.tar.gz
  sha256: 83c59a33ebc147fd682e021bdecdbfbeb4902761734bcf609d27131971a44e9b

build:
  skip: true  # [py<39 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make  # [not win]
    - ninja  # [win]
    - cmake >=3.14
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - setuptools >=42
    - wheel
    - numpy
    - pip
  run:
    - python
    - numpy
    - scikit-learn >=1.2.2
    - jax
    - nlopt

test:
  imports:
    - skscope
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://skscope.readthedocs.io"
  summary: Sparsity-Constraint OPtimization via itErative-algorithm
  license: MIT
  license_file: LICENSE
  doc_url: https://skscope.readthedocs.io
  dev_url: https://github.com/abess-team/skscope
  description: |
    skscope (Sparsity-Constraint OPtimization via itErative-algorithm) aims to make sparsity-constrained optimization (SCO)
    accessible to everyone because SCO holds immense potential across various domains,
    including machine learning, statistics, and signal processing. By providing a user-friendly interface, 
    skscope empowers individuals from diverse backgrounds to harness the power of SCO and unlock its broad range of applications.

extra:
  recipe-maintainers:
    - bbayukari
